### ISSUE TITLE
add question number to folder name

### ISSUE THREAD

**Issue by jennny06** [3ba2ii/LeetSync#10]
**Describe the solution you'd like**
Hey, could you add question number to the folder number? like `1-two-sum`. This would help a lot, so I can find questions easier.

**Comment by darshan-trivedi-10** [comment]
I also need this feature

**Comment by 3ba2ii** [comment]
Hello @jennny06, Thanks a lot for your suggestion. Gonna add that in the next version of course.

Stay tuned!

**Comment by 3ba2ii** [comment]
Hello @jennny06, This feature is now included in version 0.0.4, Please update the extension and let me know if everything is working alright
