### ISSUE TITLE
I get a repository not found error every time trying to link a repo

### ISSUE THREAD

**Issue by sbaeyens** [3ba2ii/LeetSync#13]
![image](https://github.com/3ba2ii/LeetSync/assets/11000112/3bb3729e-70f9-4440-a41b-988540147833)

I've tried making the repo public and tried all available linking options.

**Comment by 3ba2ii** [comment]
Hello @sbaeyens, Did you tried using a link like this`https://github.com/sbaeyens/leeycode-practice`, Notice without `.git` at the end

**Comment by morpheus-30** [comment]
> Hello @sbaeyens, Did you tried using a link like this`https://github.com/sbaeyens/leeycode-practice`, Notice without `.git` at the end

That works! Thanks, it must be mentioned in the hint text.
