### ISSUE TITLE
Syncing to Different Subdirectory / Repository

### ISSUE THREAD

**Issue by singh3abhi** [3ba2ii/LeetSync#14]
Hello there!

I was testing the latest feature "Set a subdirectory" and I encountered some bugs
1) Sometimes when I change the subdirectory and try to submit new questions, It is stored in the previous subdirectory only.
2) Submitted question's subdirectory doesn't change.
3) Once I changed my GitHub repo and submitted questions and saw that solution to new questions was committing to the previous repository.

![WhatsApp Image 2023-05-16 at 2 05 00 AM (1)](https://github.com/3ba2ii/LeetSync/assets/99040717/4ab7ad89-98b8-4b4a-af60-33c53c45bc52)
![WhatsApp Image 2023-05-16 at 2 04 13 AM (1)](https://github.com/3ba2ii/LeetSync/assets/99040717/96983f5d-b23c-41f2-889b-8264a9945976)

**Comment by 3ba2ii** [comment]
Hello @singh3abhi, Does this issue still exist?
