### ISSUE TITLE
The number of questions solved is not updating.

### ISSUE THREAD

**Issue by mehul2015** [3ba2ii/LeetSync#25]

**Comment by jaydeep-pro** [comment]
same with me

**Comment by skccharan** [comment]
yes indeed

**Comment by jeffliu007** [comment]
not working

**Comment by 3ba2ii** [comment]
Hello @mehul2015, Thanks a lot for reporting that, I fixed the issue and uploaded a new version to the store, It should be fixed right now, Just update the extension and let me know if the problem is fixed or not

**Comment by mehul2015** [comment]
All good now, thanks @3ba2ii
