### ISSUE TITLE
Commits stopped working as of today

### ISSUE THREAD

**Issue by jeffliu007** [3ba2ii/LeetSync#27]
Leetsync commits stopped committing today but was working fine yesterday. Tried linking and unlinking different repos and tried new questions on LC but nothing worked.

**Comment by 3ba2ii** [comment]
Hello @jeffliu007, Thanks a lot for reporting that, I fixed the issue and uploaded a new version to the store, It should be fixed right now, Just update the extension and let me know if the problem is fixed or not

**Comment by jeffliu007** [comment]
Working now!
