### ISSUE TITLE
Not syncing all solutions

### ISSUE THREAD

**Issue by sebbii17** [3ba2ii/LeetSync#3]
I solved two LeetCode problems today, but only the first one got synced with the extension.

**Comment by sebbii17** [comment]
I tried with both UI versions

**Comment by 3ba2ii** [comment]
Hello @sebbii17

A new release that should fix this issue and introduces new features is just pushed to Google Chrome Web Store, It will be reviewed and published in a couple of days, Stay tuned 🙌

**Comment by 3ba2ii** [comment]
Hello @sebbii17, The release is now published on chrome web store, can you update the extension and tell me if the problem persists or not?

**Comment by sebbii17** [comment]
@3ba2ii problem is solved and everything is working perfect now!
