### ISSUE TITLE
Would like to be able to work retroactively 

### ISSUE THREAD

**Issue by emilyhopegrove** [3ba2ii/LeetSync#5]
It would be really nice to be able to have a problem from leetcode that has already been solved count and be pushed to github.

**Comment by 3ba2ii** [comment]
Hello @emilyhopegrove, Thank a lot for your contribution, I guess this is gonna be a little tricky as we don't store the use's solved problem in our database or something, Its all stored on the chrome sync storage (Which is limited), and this can cause issues to store all these problem.
