### ISSUE TITLE
Submission duplicates

### ISSUE THREAD

**Issue by hebaghazali** [3ba2ii/LeetSync#6]
I'm not sure if this issue is unique to me, but I noticed that each solution is being committed and pushed multiple times even though I only submit it once.

![image](https://user-images.githubusercontent.com/43419199/233870235-5b285780-9a59-47bd-90e1-ffaedf3e8fcb.png)

**Comment by 3ba2ii** [comment]
Hello @hebaghazali

Thanks a lot for keeping an eye for this, Can you please clarify if this always the case or was just temporarily bug?

**Comment by hebaghazali** [comment]
Yes, it seems that the issue was temporary, I'm no longer experiencing the same problem. I've been submitting more solutions, and they're being committed only once as expected. Thank you for looking into this!
