### ISSUE TITLE
Dart Submission Not Being Sync

### ISSUE THREAD

**Issue by BoonHianLim** [3ba2ii/LeetSync#7]
**Describe the bug**
Any dart submission submitted will not be synced to the repository.

**To Reproduce**
1. Use LeetCode new Interface
2. Go to any LeetCode question (for me, I used https://leetcode.com/problems/invert-binary-tree/description/)
3. Submit the correct code (for me, I submitted as follows:
```
class Solution {
   TreeNode? invertTree(TreeNode? root) {
    return root == null ? root : TreeNode(root.val, invertTree(root.right), invertTree(root.left));
  }
}
```
)
4. Click submit
5. Leetcode verifies the solution is correct, but the submission does not show up in the linked repository,

**Screenshots**
![image](https://user-images.githubusercontent.com/101855951/235308092-fb4cbd31-633f-4e8d-871d-beaefe82ca31.png)
- Submitted solution in dart
![image](https://user-images.githubusercontent.com/101855951/235308147-ed4466ec-7d9a-4743-89a6-675e5c2c23ed.png)
- Submitted solution not showing in the repository.

**Additional Information**
Submission written in typescript is recorded by LeetSync successfully, but submission written in Dart doesn't.

**Comment by 3ba2ii** [comment]
Hello @BoonHianLim,

Thanks a lot for reporting this, The new version release [(0.0.3)](https://github.com/3ba2ii/LeetSync/releases/tag/0.0.3) should fix this issue, Its now in review at Google Chrome Extensions Store (Takes 2-3 days to review), And will be published for everyone to use afterwards

Stay tuned!

**Comment by 3ba2ii** [comment]
Hello @BoonHianLim,

Version 0.0.3 is now published, And should fix this, Please let me know if anything goes wrong

Thanks!
