### ISSUE TITLE
In the Readme, pls add the the leetcode problem link

### ISSUE THREAD

**Issue by bugsurfer** [3ba2ii/LeetSync#8]
Something like this would help in accessing the leetcode problem quickly.
And also if possible pls add the problem code at the start
<img width="1113" alt="Screenshot 2023-05-01 at 10 45 09 PM" src="https://user-images.githubusercontent.com/18248253/235495003-f3c53f77-b881-4a03-b7be-575dd71f2aa8.png">

**Comment by 3ba2ii** [comment]
Hello @bugsurfer 

Thanks a lot for reporting this, The new version release [(0.0.3)](https://github.com/3ba2ii/LeetSync/releases/tag/0.0.3) should improve the README files generated, Will add Problem Name and difficulty badge as well.

The release is now in review at Google Chrome Extensions Store (Takes 2-3 days to review), And will be published for everyone to use afterwards

Stay tuned!

**Comment by 3ba2ii** [comment]
Hello @bugsurfer,

Version 0.0.3 is now published, And should fix this, Please let me know if anything goes wrong

Thankss
